markdown: rdiscount
permalink: /:title/
url: http://www.dnp.wf
name: DNP No-Woven 
author: Ningbo DNP No-Woven Co,.Ltd.
email: tangjj@dnp.wf
duoshuo: dnp
beian: 浙ICP备14026618号
cnzz: 1252910457
github: tangjj
safe: false
paginate: 20
