markdown: rdiscount
permalink: /:title/
url: http://www.nonwovenfabric.biz/
name: DNP Non-Woven Fabric
author: Ningbo DNP Non-Woven Co,.Ltd.
email: tangjj@dnp.wf
duoshuo: dnp
beian: 浙ICP备14026618号
cnzz: 1252910457
github: tangjj
safe: false
paginate: 20
gems: [jekyll-paginate]
